/suave_runner_node:
  ros__parameters:
    result_path: '~/suave/results'
    gui: false # Enable GUI
    experiment_logging: true # Enable silent mode
    run_duration: 350 # max duration before aborting (needed for when something crashes)
    mission_config_pkg: 'suave_missions'
    mission_config_file: 'config/planta_exp1_mission_config.yaml'
    water_visibility_sec_shift: 0.0
    water_visibility_sec_shift_random_interval: [0.0, 0.0] # increase these values to increase the state, match the period
    thruster_events: 
      - (1,failure,100)
      - (3,failure,100) # choose a thruster that really makes it bad
    thruster_events_random_interval: [-100.0, 100.0]
    random_interval: 5 # how many experiment runs in each "random" interval
    initial_pos_x: -17.0
    initial_pos_y: 2.5
    initial_pos_x_random_interval: [0.0, 0.0]
    initial_pos_y_random_interval: [-0.5, 0.5]
    experiments: # List of experiments to run
      - |
        {
          "experiment_launch": "ros2 launch suave_planta suave_planta_extended.launch.py",
          "num_runs": 2,
          "adaptation_manager": "planta",
          "mission_name": "suave_extended"
        }
      - |
        {
          "experiment_launch": "ros2 launch suave_rosa_bt suave_rosa_extended_bt.launch.py",
          "num_runs": 2,
          "adaptation_manager": "rosa_bt",
          "mission_name": "suave_extended"
        }
      - |
        {
          "experiment_launch": "ros2 launch suave_bt suave_bt_extended.launch.py",
          "num_runs": 2,
          "adaptation_manager": "bt",
          "mission_name": "suave_extended"
        }

