/analysis:
  ros__parameters:
    result_path: '~/suave_ws/src/suave_planta/results/suave/exp2'
    filename: 'suave_analysis'
    data_files: # List of data_file to analyze
      - |
        {
          "managing_system": "none",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/none_suave.csv"
        }
      - |
        {
          "managing_system": "random",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/random_suave.csv"
        }
      - |
        {
          "managing_system": "bt",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/bt_suave.csv"
        }
      - |
        {
          "managing_system": "metacontrol",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/metacontrol_suave.csv"
        }
      - |
        {
          "managing_system": "rosa",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/rosa_bt_suave.csv"
        }
      - |
        {
          "managing_system": "planta",
          "data_file": "~/suave_ws/src/suave_planta/results/suave/exp2/planta_suave.csv"
        }

